
server:
  port: 9001
spring:
  application:
    name: DRIVER-SERVICE
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/driverdb
    username: root
    password: 1432001Huy@!
  jpa:
    hibernate:
      ddl-auto: update  #từ động đồng bộ model với database
    generate-ddl: true
    show-sql: true