
server:
  port: 10000
spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: root
    password: 1432001Huy@!
  jpa:
    hibernate:
      ddl-auto: update  #từ động đồng bộ model với database
    generate-ddl: true
    show-sql: true